language: ruby
before_install:
  - gem install bundler -v '= 1.5.1' # http://changelog.travis-ci.com/post/71633370723/mri-ruby-2-1-0-and-jruby-1-7-9-available
before_script:
  - ./spec/setup/arangodb.sh
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - jruby-head
  - rbx-2.2.3
  - ruby-head
env:
  - ARANGODB_DISABLE_AUTHENTIFICATION=true VERSION=1.4.4
  # - ARANGODB_DISABLE_AUTHENTIFICATION=false VERSION=1.4.4
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
script: "bundle exec rake ci"
