---
Attribute:
  enabled: false
  exclude: []
BooleanParameter:
  enabled: true
  exclude: []
ClassVariable:
  enabled: true
  exclude: []
ControlParameter:
  enabled: true
  exclude: []
DataClump:
  enabled: true
  exclude: []
  max_copies: 2
  min_clump_size: 2
DuplicateMethodCall:
  enabled: true
  exclude:
  - Ashikawa::Core::ResponsePreprocessor#handle_status
  max_calls: 1
  allow_calls: []
FeatureEnvy:
  enabled: false
  exclude: []
IrresponsibleModule:
  enabled: true
  exclude: []
LongParameterList:
  enabled: true
  exclude: []
  max_params: 3
  overrides: {}
LongYieldList:
  enabled: true
  exclude: []
  max_params: 1
NestedIterators:
  enabled: true
  exclude: []
  max_allowed_nesting: 2
  ignore_iterators: []
NilCheck:
  enabled: true
  exclude:
  - Ashikawa::Core::Configuration#setup_new_connection
RepeatedConditional:
  enabled: true
  exclude:
  - Ashikawa::Core::Query
  max_ifs: 1
TooManyInstanceVariables:
  enabled: true
  exclude: []
  max_instance_variables: 12
TooManyMethods:
  enabled: true
  exclude:
  - Ashikawa::Core::Collection
  max_methods: 15
TooManyStatements:
  enabled: true
  exclude: []
  max_statements: 5
UncommunicativeMethodName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeModuleName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  accept: []
UncommunicativeParameterName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeVariableName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^[^_]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UnusedParameters:
  enabled: true
  exclude: []
UtilityFunction:
  enabled: false
  exclude: []
  max_helper_calls: 0
